export const CREATE_RESTAURANT = "CREATE_RESTAURANT";
export const RETRIVE_RESTAURANTS = "RETRIVE_RESTAURANTS";
export const UPDATE_RESTAURANT = "UPDATE_RESTAURANTS"; 
export const DELETE_RESTAURANT = "DELETE_RESTAURANT";